### PR TITLE
Update to julia 1.0 and additional functions

### PR DESCRIPTION
**Pull request by Alexander-Barth**
In this pull request I update `RTLSDR.jl` so that it is compatible with julia 1.0 and some additional low-level functions are wrapped.

### CODE REVIEW

**Comment by dressel** [comment]
Hey this is great, thanks! Do you mind if take a day or two to look it over before merging?

**Comment by Alexander-Barth** [comment]
Of course, no problem!

**Comment by dressel** [comment]
Looks good to me! Thanks a lot. Hope you've found it somewhat useful

**Comment by Alexander-Barth** [comment]
Thanks a lot! Yes, it was quite useful to me to make an FM radio receiver.

**Pull request merged**
